

const data = [
    {
        jmeno: "Jan",
        prijmeni: "Novák",
        email: "jannovak@example.com",
        plat: 35000,
        vztah: true,
        deti: 3,
        datumNarozeni: "15/05/1985",
        vek: 35,
        zkusenosti: "senior",
        vedlejsiPrijmy: 1500,
        konicky: ["sport", "hudba", "cestování"],
        ulice: "Hlavní ulice",
        mesto: "Plzeň",
        cisloPopisné: "123",
        telefon: "+420123456789",
        psc: "12345"
    },
    {
        jmeno: "Eva",
        prijmeni: "Nováková",
        email: "evanovakova@example.com",
        plat: 40000,
        vztah: false,
        deti: 1,
        datumNarozeni: "10/12/1990",
        vek: 31,
        zkusenosti: "junior",
        vedlejsiPrijmy: 800,
        konicky: ["umění", "čtení", "rybaření"],
        ulice: "Druhá ulice",
        mesto: "Plzeň",
        cisloPopisné: "456",
        telefon: "+420987654321",
        psc: "54321"
    },
    {
        jmeno: "Pavel",
        prijmeni: "Svoboda",
        email: "pavelsvoboda@example.com",
        plat: 30000,
        vztah: true,
        deti: 2,
        datumNarozeni: "20/03/1980",
        vek: 41,
        zkusenosti: "medior",
        vedlejsiPrijmy: 1200,
        konicky: ["programování", "hudba", "rybaření"],
        ulice: "Třetí ulice",
        mesto: "Plzeň",
        cisloPopisne: "789",
        telefon: "+420555666777",
        psc: "98765"
    },
    {
        jmeno: "Anna",
        prijmeni: "Králová",
        email: "annakralova@example.com",
        plat: 42000,
        vztah: false,
        deti: 0,
        datumNarozeni: "25/09/1995",
        vek: 28,
        zkusenosti: "junior",
        vedlejsiPrijmy: 600,
        konicky: ["sport", "umění", "čtení"],
        ulice: "Čtvrtá ulice",
        mesto: "Plzeň",
        cisloPopisne: "101",
        telefon: "+420111222333",
        psc: "54321"
    },
    {
        jmeno: "Martin",
        prijmeni: "Nový",
        email: "martinnovy@example.com",
        plat: 38000,
        vztah: true,
        deti: 4,
        datumNarozeni: "12/07/1982",
        vek: 41,
        zkusenosti: "medior",
        vedlejsiPrijmy: 900,
        konicky: ["cestování", "rybaření", "hudba"],
        ulice: "Pátá ulice",
        mesto: "Plzeň",
        cisloPopisné: "222",
        telefon: "+420777888999",
        psc: "77777"
    },
    {
        jmeno: "Klára",
        prijmeni: "Marešová",
        email: "klaramaresova@example.com",
        plat: 32000,
        vztah: true,
        deti: 2,
        datumNarozeni: "18/11/1990",
        vek: 32,
        zkusenosti: "senior",
        vedlejsiPrijmy: 1100,
        konicky: ["rybaření", "umění", "sport"],
        ulice: "Šestá ulice",
        mesto: "Plzeň",
        cisloPopisne: "333",
        telefon: "+420999888777",
        psc: "11111"
    },
    {
        jmeno: "Lucie",
        prijmeni: "Nová",
        email: "lucienova@example.com",
        plat: 30000,
        vztah: false,
        deti: 1,
        datumNarozeni: "22/04/1993",
        vek: 28,
        zkusenosti: "junior",
        vedlejsiPrijmy: 800,
        konicky: ["hudba", "umění", "čtení"],
        ulice: "Sedmá ulice",
        mesto: "Plzeň",
        cisloPopisne: "777",
        telefon: "+420555444333",
        psc: "65432"
    },
    {
        jmeno: "Petr",
        prijmeni: "Svobodný",
        email: "petrsvobodny@example.com",
        plat: 42000,
        vztah: true,
        deti: 2,
        datumNarozeni: "11/08/1986",
        vek: 37,
        zkusenosti: "medior",
        vedlejsiPrijmy: 1200,
        konicky: ["sport", "rybaření", "cestování"],
        ulice: "Osmá ulice",
        mesto: "Plzeň",
        cisloPopisne: "888",
        telefon: "+420888777666",
        psc: "99999"
    },
    {
        jmeno: "Veronika",
        prijmeni: "Kovářová",
        email: "veronikakovarova@example.com",
        plat: 35000,
        vztah: true,
        deti: 3,
        datumNarozeni: "05/12/1980",
        vek: 43,
        zkusenosti: "senior",
        vedlejsiPrijmy: 1500,
        konicky: ["umění", "rybaření", "hudba"],
        ulice: "Devátá ulice",
        mesto: "Plzeň",
        cisloPopisne: "999",
        telefon: "+420999888777",
        psc: "11111"
    },

]

export default data

